services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./templates:/app/templates
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - DEBUG=False
      - WKHTMLTOPDF_PATH=/usr/bin/wkhtmltopdf
    restart: unless-stopped
